### ISSUE TITLE
Minor issue 

### ISSUE THREAD

**Issue by tjhow** [kungfoo/falcon-bms-control#1]
It is working well my friend I have put Bliss OS on a Linx windows tablet and is awesome! No lag either I have only tested it for about an hour but it is great that I can access the ICP & MFD's with the touchscreen, could be even better if you had it working on Windows but I can use Bliss OS. 

The only minor issue I have had is when selecting the OSB buttons I get the language box pop up on the windows pc when flying but goes away, just a small distraction and something I can live. If there is a simple fix for this in Windows perhaps? 

Regards

**Comment by kungfoo** [comment]
This is great to hear.

Can you take a screenshot of the this popup? I don't get that, but my
Windows is set to English.

I will release a windows version of the client soon after the next version
for ios and android is built.

**Comment by kungfoo** [comment]
On ICP buttons the popup does not show?

**Comment by kungfoo** [comment]
I will add this to the FAQ: the default key binds of BMS for the osb
buttons clash with the shortcut for windows input language switching. So to
make this go away, unbind the shortcut in windows language settings.

**Comment by tjhow** [comment]
ok thanks for that
