### ISSUE TITLE
Disconnected no updates sometimes but buttons still function

### ISSUE THREAD

**Issue by tjhow** [kungfoo/falcon-bms-control#11]
I don't know whether it is my bliss android os or the app pc side but sometime when I'm flying I lose all updates to the displays but the buttons still work seems to happen on longer flights, as I said the Bliss OS isn't the most reliable to use anyway so it could be that.

**Comment by tjhow** [comment]
Yes

**Comment by kungfoo** [comment]
4.35 has a bug that sometimes the texture export stops/freezes. there is
nothing i can do about it, we'll have to wait for 4.35.1 to fix it... :/

**Comment by kungfoo** [comment]
Since this is internal to BMS 4.35, there is nothing to do here.
