### ISSUE TITLE
Problems with BMS 4.35

### ISSUE THREAD

**Issue by Renzo1952** [kungfoo/falcon-bms-control#14]
**Describe the bug**
Good day,
I downloaded and installed the Falcon BMS Control android application on my Samsung Galaxy S2 tablet and the windows server application (W10) zip file to install on the pc. I made the modification of the falcon bms.cfg file as indicated.
I launched Falcon bms 4.35 and unfortunately it crashes every time after about 30 minutes of operation.
I did the same thing for Falcon bms 4.34 and this one works perfectly.
Is there any problem with version 4.35? Any suggestions?
Thanks and best regards
Renzo

**Comment by kungfoo** [comment]
There is a problem with 4.35 that it sometimes freezes the texture export
for the MFDs. Sometimes it also flat out crashes.
It's a known issue in bms and will (hopefully) be fixed soon. Alas, there
is nothing third party apps can do as of now.

**Comment by Renzo1952** [comment]
Thanks a lot
