### ISSUE TITLE
Not working after 4.35 U1 update 

### ISSUE THREAD

**Issue by tjhow** [kungfoo/falcon-bms-control#15]
Since updating U1 the inputs do not seem to be working, nothing changes in the jet.
Can you have a look into this please and advise whether I need to make any changes or is an update required?

Regards

**Comment by kungfoo** [comment]
I will test it with 4.35.1 later today and let you know.

**Comment by kungfoo** [comment]
I just updated my install to 4.35.1 and everything works, including all the MFD and ICP buttons. Can you check the logs? Maybe it switched your keyfile over for the one that does not have keybinds for the callbacks being called.

**Comment by mudspike** [comment]
ios user. 
After updating to U1, I cannot see MFD on the screen but button input works for both MFD and ICP though. So I am currently using it as cougar mfd.

**Comment by kungfoo** [comment]
You'll need to enable rtt export in the config.

Please see here:
https://kungfoo.github.io/falcon-bms-control/

**Comment by mudspike** [comment]
Thanks!
That took care of my issue.
Somehow the value had switched back to "0" after updating to U1.

**Comment by kungfoo** [comment]
I am pretty sure that with the correct settings and the correct keyfile portions for the callbacks present, this actually works as well with 4.35.1 as it did with 4.34.x. I cannot get it to misbehave in any way with the correct config (as is documented on the linked page).
