### ISSUE TITLE
Trojan Detected !!!

### ISSUE THREAD

**Issue by bl4ckrid3r** [kungfoo/falcon-bms-control#18]
I just wanted to start the server executable and MalwareBytes flags it as Generic.Trojan.Malicious.DDS. Is it embedding something nasty ? I'm getting confused here.

I attach here Virus Total scan report :
https://www.virustotal.com/gui/file/1518bdf323b9e10d1e41b2198b24c4e6525d9344a5a607e5e964613738b4d040/detection

**Comment by kungfoo** [comment]
It is definitely not a trojan. It is using enet for communication, which is
on top of udp so maybe that is a library that is commonly used in Trojans...

**Comment by kungfoo** [comment]
Also it needs access access to windows APIs to emulate keyboard presses (to
control Falcon BMS, obviously), which might again be something a lot of
Trojans also do...

**Comment by bl4ckrid3r** [comment]
Thank you for your quick @kungfoo. I found out that only 2/69 AVs flagged it up so it has to be a false positive. Otherwise, I've just tried the app combined with the server it and it is working fine and all good.
