### ISSUE TITLE
[Feature Request] Layout adjustment on Windows client

### ISSUE THREAD

**Issue by ian-droid** [kungfoo/falcon-bms-control#23]
Thank you for the great work!

I just wondering if it's possible to adjust the layout of the Windows client? I have no other hardware panel and using the Windows client with my touch enabled 14' laptop, but I can't have all the instruments in one page. 

With pervious version client (1.2.0) looks like it's possible to run two instances with one page each, but seems 1.3.1 forces into full screen so only one instance is accessible at one time. Is there any workaround for this, such as parameter for disabling full screen?

Thanks!

**Comment by kungfoo** [comment]
You should be able to exit full screen either using window controls or
alt-enter. Let me know if that does not work for you.

Custom layouts are likely to be supported in the next version, if I can
make them universally applicable.

**Comment by kungfoo** [comment]
I assume ALT+ENTER works.
