### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jhl6** [kungfoo/falcon-bms-control#24]
Hello Silvio,

I have a question.
I'm building a hardware system to connect switches and buttons to Falcon BMS.
The hardware is ready, but the software is a problem. (writing in C#)
Would you share with me how your server is connecting and sending commands to BMS?
Maybe you have a example for me.

With kind regards,
Jan Hein

**Comment by kungfoo** [comment]
You can check Helios for how to send keystrokes to BMS according to what's
in the active keyfile:

https://github.com/HeliosVirtualCockpit/Helios/tree/master/HeliosFalcon/Interfaces

I'm using a similar, but not identical method. If you GPL (open source)
your code, you can copy straight from Helios.
