### ISSUE TITLE
4.36 U2 no display

### ISSUE THREAD

**Issue by gabrielwong1991** [kungfoo/falcon-bms-control#25]
Hi in 4.36 U2 there is no display on the app but all the control works. Can you look into it Kungfoo?

Thanks!

**Comment by kungfoo** [comment]
You'll have to re-enable RTT export in your bms config. The update can
overwrite it.

**Comment by kungfoo** [comment]
- Enable RTT exports in ${falcon bms install}/user/config/falcon_bms.cfg:
   set g_bExportRTTTextures 1

Or even better, enable it in your user config, so it'll survive the next
update.

**Comment by gabrielwong1991** [comment]
Ah sorry Kungfoo I missed that, thanks!
