### ISSUE TITLE
[Feature Request] consolidated/1-screen view?

### ISSUE THREAD

**Issue by protocolGITHUB** [kungfoo/falcon-bms-control#27]
great program(s)!  makes Falcon BMS alot more fun.

Any chance of a 'consolidated/1-screen' view option
Redo the ICP into 3 or 4 rows of buttons above the MFD left, and the DED above the MFD right?

either way, thanks for the great work!

ps: +1 request to release the source :)

**Comment by kungfoo** [comment]
Thinking about addressing this in #32 in a generic manner.

**Comment by kungfoo** [comment]
This is definitely going to be in the next client version 1.4.
