### ISSUE TITLE
F-15C Compatibility

### ISSUE THREAD

**Issue by SammySkycrafts** [kungfoo/falcon-bms-control#29]
F-15C has some issues with the app. Both the MPCD and Radar display are sent to the app, however the "OSB's" are inverted, so if you click one of the right OSB's, where the MPCD is shown, nothing happens. You need to press the equivalent on the left screen for the command to be sent.

**Comment by kungfoo** [comment]
I'll have so see see what i can do about this. I am currently away from my
bms machine,  but maybe i can sort it out.

**Comment by SammySkycrafts** [comment]
Closing as issue appears to no longer be a thing.

Possibly was a keyfile issue, or maybe something was quietly changed in one of the U3 hotfixes.
