### ISSUE TITLE
4:3 device button problem

### ISSUE THREAD

**Issue by atomic76** [kungfoo/falcon-bms-control#3]
The left MFD and the right MFD are too close to cause a mistake when the button is pressed.
Can't you make a space in the middle?
![12](https://user-images.githubusercontent.com/56898639/103596647-c0243900-4f41-11eb-8f4f-96ce8ffa26de.jpg)

**Comment by kungfoo** [comment]
Yes, this is already in the works for the next patch version.

**Comment by atomic76** [comment]
Thanks! 👍

**Comment by kungfoo** [comment]
This fix is rolled out with the newest app version `1.1.0`
