### ISSUE TITLE
[Not A Feature Request] Just a thank you

### ISSUE THREAD

**Issue by sophisma** [kungfoo/falcon-bms-control#36]
I know GitHub is not for this but I just wanted to thank you for what you did, this is a game changer.
I'm a new player player to BMS and used to have to change between the stick and the mouse to dance around the MFD buttons, now I can just "press" them.
What a Legend,

**Comment by kungfoo** [comment]
Thank you so much for your kind words. It's always cool to know people are enjoying the app.
