### ISSUE TITLE
[Feature Request] Config Option

### ISSUE THREAD

**Issue by Locolumbie90** [kungfoo/falcon-bms-control#38]
I'm having issues with the client not discovering the server over a LAN on Windows.

Would be great if I could enter the setup menu before the app try to connect. 

Or to have the posiblity to set the server IP manualy in the client config file via text editor.

**Comment by kungfoo** [comment]
You can enter the server ip on the 'connecting' screen, just go tap the cog
wheel.
From then on it will remember said ip and connect straight to it.

I'm not sure how else you want to enter the ip before it connects, maybe
you can elaborate how this current solution isn't working for you?

**Comment by kungfoo** [comment]
The current version already allows config changes on the first screen.
