### ISSUE TITLE
Stuck on Discovering server

### ISSUE THREAD

**Issue by kcmbklyn** [kungfoo/falcon-bms-control#39]
Been working at this a bit and cant seem to solve. Windows server program has firewall permissions. Both Ipad and PC are on same Wifi. Changed the correct config file from 0 - 1. Cannot discover server on automatic. I tried entering IP numbers but im a bit of a noob but I tried 10.0.0.xx - I assume that is the correct IP number. Tried running the server in admin mode. Still not connecting. By contrast BMSNav ios app and server connected to eachother and worked immmediately when I connected via 10.0.0.xx. Any thoughts on what else I can try? Thanks!

**Comment by kungfoo** [comment]
Can you find out the ip of the pc with `ipconfig \all`?
If you enter the ip correctly and the server is running it's 99% percent
chance it's a firewall issue.

**Comment by kungfoo** [comment]
Assuming this was solved.
