### ISSUE TITLE
Vibration setting is not working

### ISSUE THREAD

**Issue by atomic76** [kungfoo/falcon-bms-control#5]
**Describe the bug**
I just tested the latest version.
Button vibration option is not working.
Whether the option is on or off, vibration is always on.

**To Reproduce**
1. Go to 'setting page'
2. Click on 'vibration off'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi PAD
 - OS: Android 4.4
 - App version: 1.1.0

**Additional context**

**Comment by kungfoo** [comment]
It is already fixed in 1.1.1 which is currently in review.
