### ISSUE TITLE
shorter vibration 

### ISSUE THREAD

**Issue by atomic76** [kungfoo/falcon-bms-control#6]
**Is your feature request related to a problem? Please describe.**
It feels like I'm getting a call when I press the button several times. :)

**Describe the solution you'd like**
I think the vibration is a bit long when pressing button, so please make the vibration a little shorter.
Well, I think it'll be great if it feels like pressing the home button on the iPhone.
Or, I hope it's similar to the vibrating feeling when press the Android bottom navigation button.

**Comment by kungfoo** [comment]
1.1.1 already has a shortened vibration time down to 100ms. Maybe to
produce the feel you want it needs to be even shorter.
