### ISSUE TITLE
Only seeing static content

### ISSUE THREAD

**Issue by Andytr1** [kungfoo/falcon-bms-control#7]
Hello,
Thank you for the great app. I am running it on an Android table in landscape mode. I am able to see static content - MFD buttons, ICP buttons and they work inside the game.
However, I am not seeing any MFD pages or DED being rendered on the Android device. Is there a setting I am missing?

Thank you!

**Comment by kungfoo** [comment]
You are probably missing the setting to enable RTT exports:

> Enable RTT exports in ${falcon bms install}/user/config/falcon_bms.cfg: set g_bExportRTTTextures 1

**Comment by Andytr1** [comment]
Thank you. That was it!
